[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[cursor]
unfocused_hollow = true

[font]
size = 10.0

[font.normal]
family = "Monaspace Neon Var"
style = "Regular"

[mouse]
hide_when_typing = false

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window.dimensions]
columns = 160
lines = 50
